[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlight-host = { workspace = true }
hyperlight-common = { workspace = true }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
