[package]
name = "guest-async"
version = "0.1.0"
edition = "2021"

[dependencies]
hl-guest = { workspace = true }
hl-guest-async = { workspace = true }
futures = { version = "0.3", default-features = false, features = ["alloc", "async-await"] }
